# Generated by Django 3.2.9 on 2021-11-13 04:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0008_action_rating'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='action',
            unique_together={('creator', 'lesson')},
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('creator', 'lesson')},
        ),
    ]
